import type { Metadata } from "next";
import { Russo_One} from "next/font/google";
import "./globals.css";


const oxanium = Russo_One({weight:["400"],subsets:["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${oxanium.className} antialiased dark`}
      >
        {children}
      </body>
    </html>
  );
}
